### ISSUE TITLE
Error on NPM start - socket hang up 

### ISSUE THREAD

**Issue by Tzikas** [hknd/redux-twitter-stream-demo#1]
Hi I created a twitter.config.js file with the appropriate fields in the root of the application, but i got the following when running npm start. 

```
Listening at http://localhost:3000
{ [Error: socket hang up] code: 'ECONNRESET' }
webpack built c1264b2c36f5efa14120 in 24748ms
Hash: c1264b2c36f5efa14120
Version: webpack 1.15.0
Time: 24748ms
    Asset       Size  Chunks       Chunk Names
bundle.js    1.57 MB       0       main
  app.css  691 bytes       0       main
chunk    {0} bundle.js, app.css (main) 1.33 MB [rendered]
```

I also tried updated all modules but then received this error 

`WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve.extensions[0] should not be empty.`

**Comment by asndev** [comment]
Will rewrite this example with up2date packages soon

**Comment by asndev** [comment]
Updated using create-react-app.
